//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.12

pub mod prelude;

pub mod category;
pub mod permission;
pub mod role;
pub mod role_permission;
pub mod user;
pub mod user_role;
pub mod word;
pub mod word_category;
pub mod word_english;
pub mod word_slovene;
pub mod word_translation;
pub mod word_translation_suggestion;
