//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.12

pub use super::permission::Entity as Permission;
pub use super::role::Entity as Role;
pub use super::role_permission::Entity as RolePermission;
pub use super::user::Entity as User;
pub use super::user_role::Entity as UserRole;
pub use super::word::Entity as Word;
pub use super::word_english::Entity as WordEnglish;
pub use super::word_slovene::Entity as WordSlovene;
pub use super::word_translation::Entity as WordTranslation;
pub use super::word_translation_suggestion::Entity as WordTranslationSuggestion;
