//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.12

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "word_slovene"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub word_id: Uuid,
    pub lemma: String,
    pub disambiguation: Option<String>,
    pub description: Option<String>,
    pub added_at: DateTimeWithTimeZone,
    pub last_edited_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    WordId,
    Lemma,
    Disambiguation,
    Description,
    AddedAt,
    LastEditedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    WordId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Word,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::WordId => ColumnType::Uuid.def(),
            Self::Lemma => ColumnType::String(None).def(),
            Self::Disambiguation => ColumnType::String(None).def().null(),
            Self::Description => ColumnType::String(None).def().null(),
            Self::AddedAt => ColumnType::TimestampWithTimeZone.def(),
            Self::LastEditedAt => ColumnType::TimestampWithTimeZone.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Word => Entity::belongs_to(super::word::Entity)
                .from(Column::WordId)
                .to(super::word::Column::Id)
                .into(),
        }
    }
}

impl Related<super::word::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Word.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
