[package]
name = "stari-kolomoni-backend"
description = "Backend system for the Stari Kolomoni fantasy translation project."
license-file = "LICENSE.md"
version = "0.1.0"
edition = "2021"
authors = ["Grimpy101 <gorupgorazd@gmail.com>", "Simon Goričar <simon.peter.goricar@gmail.com>"]
rust-version = "1.65.0"

[workspace]
members = [".", "migrations"]

[[bin]]
name = "stari-kolomoni-backend"
path = "./src/main.rs"

[dependencies]
migration = { path = "migrations" }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.97"
actix-web = "4.3.1"
tracing-actix-web = "0.7.5"
thiserror = "1.0.40"
anyhow = "1.0.71"
argon2 = "0.5.0"
dunce = "1.0.4"
toml = "0.7.4"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
sea-orm = { version = "^0", features = [ "sqlx-postgres", "runtime-tokio-rustls", "macros", "with-chrono" ] }
utoipa = { version = "3.3.0", features = ["actix_extras"] }
tokio = { version = "1.28.2", features = ["full"] }
chrono = "0.4.26"
jsonwebtoken = "8.3.0"
serde_with = { version = "3.0.0", features = ["chrono"] }
actix-utils = "3.0.1"
clap = { version = "4.3.8", features = ["derive"] }
