[package]
name = "stari-kolomoni-backend"
description = "Backend system for the Stari Kolomoni fantasy translation project."
license-file = "LICENSE.md"
version = "0.1.0"
edition = "2021"
authors = ["Grimpy101 <gorupgorazd@gmail.com>", "Simon Goričar <simon.peter.goricar@gmail.com>"]
rust-version = "1.65.0"

[workspace]
members = [".", "migrations", "openapi"]

[[bin]]
name = "stari-kolomoni-backend"
path = "./src/main.rs"

[dependencies]
migration = { path = "migrations" }
clap = { version = "4.4.18", features = ["derive"] }
thiserror = "1.0.56"
anyhow = "1.0.79"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
serde_with = { version = "3.6.0", features = ["chrono"] }
tokio = { version = "1.36.0", features = ["full"] }
actix-web = "4.4.1"
actix-utils = "3.0.1"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tracing-actix-web = "0.7.9"
sea-orm = { version = "0.12.2", features = [ "sqlx-postgres", "runtime-tokio-rustls", "macros", "with-chrono" ] }
argon2 = "0.5.3"
dunce = "1.0.4"
toml = "0.8.9"
chrono = "0.4.33"
jsonwebtoken = "9.2.0"
utoipa = { version = "4.2.0", features = ["actix_extras", "chrono", "preserve_order"] }
actix-cors = "0.7.0"
