[config]
default_to_workspace = false
skip_core_tasks = true
skip_crate_env_info = true
skip_git_env_info = true
skip_rust_env_info = true
min_version = "0.37.9"

[env]
CARGO_MAKE_USE_WORKSPACE_PROFILE = false




[tasks."database:initialize"]
clear = true
workspace = false
condition = { platforms = ["windows"]}
command = "pwsh"
args = [
    "./scripts/database/init-database.ps1"
]



[tasks."database:run"]
clear = true
workspace = false
condition = { platforms = ["windows"]}
command = "pwsh"
args = [
    "./scripts/database/run-database.ps1"
]

[tasks."database:start"]
clear = true
workspace = false
condition = { platforms = ["windows"]}
command = "pwsh"
args = [
    "./scripts/database/manually-start-database.ps1"
]

[tasks."database:stop"]
clear = true
workspace = false
condition = { platforms = ["windows"]}
command = "pwsh"
args = [
    "./scripts/database/manually-stop-database.ps1"
]




[tasks.build-and-open-full-documentation]
clear = true
workspace = true
command = "cargo"
args = [
    "doc",
    "--workspace",
    "--open"
]


[tasks."backend:run"]
clear = true
workspace = true
command = "cargo"
args = ["run", "--release"]
cwd = "."

[tasks."backend:openapi:run"]
clear = true
workspace = true
command = "cargo"
args = ["run", "--release"]
cwd = "./kolomoni_openapi"



[tasks.build-and-watch-workspace-documentation-with-private-items]
clear = true
workspace = true
command = "cargo"
args = [
    "watch",
    "--exec",
    "doc --workspace --no-deps --document-private-items"
]



[tasks.documentation]
clear = true
workspace = true
alias = "doc"
dependencies = [
    "build-and-open-full-documentation",
    "build-and-watch-workspace-documentation-with-private-items"
]
