[package]
name = "kolomoni_search"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kolomoni_search_core = { path = "../kolomoni_search_core" }
kolomoni_core = { path = "../kolomoni_core" }
kolomoni_database = { path = "../kolomoni_database" }
kolomoni_cache = { path = "../kolomoni_cache" }
kolomoni_configuration = { path = "../kolomoni_configuration" }

# sea-orm = { workspace = true }
tokio = { workspace = true }

tantivy = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }

slotmap = { workspace = true }
chrono = { workspace = true }

parking_lot = { workspace = true }
crossbeam-channel = { workspace = true }
