###
# Migration
#   version 0001
#   name    prepare-database
#
# Created on: 2024-09-01T14:20:11Z
###
#
# Note that it is impossible to modify the version or name of the migration in 
# this configuration file *by design*. Both the version and name are 
# *always* parsed from the parent directory name for consistency.
#


# Whether to run the migration (up and down) as a privileged user instead of the normal user.
# Depending on setup, this might be required for things like creating databases and granting permissions.
run_as_privileged_user = true


##
# Configuration that impacts the up.sql migration script.
##
[up]
# Certain statements, such as CREATE INDEX CONCURRENTLY, cannot be run inside a transaction.
# Using those statements in your migration script will require you to run the migration
# without a transaction.
run_inside_transaction = true



##
# Configuration that impacts the down.sql rollback script.
##
[down]
# Certain statements, such as CREATE INDEX CONCURRENTLY, cannot be run inside a transaction.
# Using those statements in your migration script will require you to run the migration
# without a transaction.
run_inside_transaction = true
