//! This crate contains raw database entities in combination
//! with the "business logic", i.e. query and mutation methods for them.
//!
//! *Do not query or mutate the models by hand! Use the querying and mutation
//! implementations in the [`query`] and [`mutation`] modules instead!*
//!
//! The entitites in [`entities`] must be auto-generated by `sea-orm-cli`;
//! for more information, consult the README.
//!
//! Additional `impl` blocks for the auto-generated entities are present in the [`impls`] module.

pub mod entities;
mod impls;
pub mod macros;
pub mod mutation;
pub mod query;
pub mod shared;
