//! This crate contains raw database entities in combination
//! with the "business logic", i.e. query and mutation methods for them.
//!
//! *Do not query or mutate the models by hand! Use the querying and mutation
//! implementations in the [`crate::query`] and [`crate::mutation`] modules instead!*
//!
//! The entitites in [`crate::entities`] must be auto-generated by `sea-orm-cli`;
//! for more information, consult the README.

pub mod entities;
pub mod mutation;
pub mod query;
