[package]
name = "kolomoni_test_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kolomoni_core = { path = "../kolomoni_core", features = ["serde_impls_for_client_on_models", "e2e-testing"] }
kolomoni_api_client = { path = "../kolomoni_api_client" }
kolomoni_database = { path = "../kolomoni_database" }
kolomoni_configuration = { path = "../kolomoni_configuration" }

kolomoni_test_macros = { path = "../kolomoni_test_macros" }

actix-web = { workspace = true }
actix-http = { workspace = true }
actix-cors = { workspace = true }
actix-service = { workspace = true }

reqwest = { workspace = true }
chrono = { workspace = true }
assert_matches = { workspace = true }

tracing-actix-web = { workspace = true }

miette = { workspace = true }
tokio = { workspace = true }

bytes = { workspace = true }
uuid = { workspace = true }
