use std::{future::Future, marker::PhantomData};

use crate::{
    client::KolomoniHttpClient,
    request::raw::{BoundRawRequest, RawRequest},
    response::{raw::RawResponse, IntoTypedResponse, ResponseValueError, TypedResponse},
    BoxFuture,
};

/// A strongly-typed version of [`RawRequest`] which attaches
/// three things:
/// - an async closure, whose job it will be to parse a [`RawResponse`] into the output type `Result<V, E>`,
/// - the type `V`, which is the parsed output value type (generated by the parser closure), and
/// - the type `E`, which is the error type (generated by the parser closure or by conversion from bubbled errors
///   from the request preparation or execution stages, which is why `E` must implement [`ResponseValueError`]).
pub struct TypedRequest<V, E>
where
    E: ResponseValueError,
{
    raw_request: RawRequest,

    response_parser_closure: Box<dyn FnOnce(RawResponse) -> BoxFuture<'static, Result<V, E>>>,

    _marker_v: PhantomData<V>,
    _marker_e: PhantomData<E>,
}

impl<V, E> TypedRequest<V, E>
where
    E: ResponseValueError,
{
    #[inline]
    pub(crate) fn new<F, Fut>(request: RawRequest, parser_closure: F) -> Self
    where
        F: FnOnce(RawResponse) -> Fut + 'static,
        Fut: Future<Output = Result<V, E>> + Send + 'static,
    {
        let prepared_closure: Box<dyn FnOnce(RawResponse) -> BoxFuture<'static, Result<V, E>>> =
            Box::new(move |data: RawResponse| Box::pin(parser_closure(data)));

        Self {
            raw_request: request,
            response_parser_closure: prepared_closure,
            _marker_v: PhantomData,
            _marker_e: PhantomData,
        }
    }
}

impl<V, E> AsRef<RawRequest> for TypedRequest<V, E>
where
    E: ResponseValueError,
{
    fn as_ref(&self) -> &RawRequest {
        &self.raw_request
    }
}

impl<V, E> AsMut<RawRequest> for TypedRequest<V, E>
where
    E: ResponseValueError,
{
    fn as_mut(&mut self) -> &mut RawRequest {
        &mut self.raw_request
    }
}


pub trait IntoTypedRequest<V, E>
where
    E: ResponseValueError,
{
    fn into_typed_request<F, Fut>(self, parser_closure: F) -> TypedRequest<V, E>
    where
        F: FnOnce(RawResponse) -> Fut + 'static,
        Fut: Future<Output = Result<V, E>> + Send + 'static;
}

impl<V, E> IntoTypedRequest<V, E> for RawRequest
where
    E: ResponseValueError,
{
    fn into_typed_request<F, Fut>(self, parser_closure: F) -> TypedRequest<V, E>
    where
        F: FnOnce(RawResponse) -> Fut + 'static,
        Fut: Future<Output = Result<V, E>> + Send + 'static,
    {
        TypedRequest::new(self, parser_closure)
    }
}



/// A version of [`TypedRequest`] that additionally
/// captures the `C: `[`KolomoniHttpClient`] that will be
/// used to execute the request.
///
/// This is the return type of most API endpoint function across
/// this crate, because you, the user, can now simply call [`Self::send`],
/// which will execute the request and parse the response into the output value `V` or
/// bubbling up all the errors from the previous stages into `E`.
pub struct BoundTypedRequest<'c, C, V, E>
where
    C: KolomoniHttpClient,
    E: ResponseValueError,
{
    client: &'c C,
    request: TypedRequest<V, E>,
}

impl<'c, C, V, E> BoundTypedRequest<'c, C, V, E>
where
    C: KolomoniHttpClient,
    V: 'static,
    E: ResponseValueError + 'static,
{
    pub(crate) fn new(client: &'c C, request: TypedRequest<V, E>) -> Self {
        Self { client, request }
    }

    /// Returns a reference to the underlying raw HTTP request.
    pub fn request(&self) -> &RawRequest {
        &self.request.raw_request
    }

    /// Returns a mutable reference to the underlying raw HTTP request,
    /// allowing you to modify the concrete request before it's sent.
    pub fn request_mut(&mut self) -> &mut RawRequest {
        &mut self.request.raw_request
    }

    /// Sends the prepared request and parses the response directly into `Result<V, E>`,
    /// bubbling up any errors that happened during the request's preparation, execution,
    /// or parsing stage into `E`.
    ///
    /// **If you're unfamiliar with this crate and the return type of most endpoints:
    /// this is the recommended way of sending the request to the API.**
    pub async fn send(self) -> Result<V, E> {
        self.client
            .send(self.request.raw_request)
            .await
            .into_typed_response(self.request.response_parser_closure)
            .try_into_value()
            .await
    }

    /// Sends the prepared request and stores the response into [`TypedResponse`]`<V, E>`,
    /// bubbling up any errors that happened during the request's preparation or execution.
    ///
    /// **This is generally not used during "normal" uses of this crate** (use [`Self::send`] instead),
    /// since this crate does all the parsing for you. This method will allow you to inspect
    /// the underlying raw HTTP response manually before parsing the output value,
    /// which is useful mostly for debugging and testing.
    pub async fn send_and_get_response(self) -> TypedResponse<V, E> {
        self.client
            .send(self.request.raw_request)
            .await
            .into_typed_response(self.request.response_parser_closure)
    }
}

impl<'c, C, V, E> AsRef<TypedRequest<V, E>> for BoundTypedRequest<'c, C, V, E>
where
    C: KolomoniHttpClient,
    E: ResponseValueError,
{
    fn as_ref(&self) -> &TypedRequest<V, E> {
        &self.request
    }
}

impl<'c, C, V, E> AsMut<TypedRequest<V, E>> for BoundTypedRequest<'c, C, V, E>
where
    C: KolomoniHttpClient,
    E: ResponseValueError,
{
    fn as_mut(&mut self) -> &mut TypedRequest<V, E> {
        &mut self.request
    }
}


pub trait IntoBoundTypedRequest<'c, C, V, E>
where
    C: KolomoniHttpClient,
    E: ResponseValueError,
{
    /// Consumes and converts `self` into a [`BoundTypedRequest`],
    /// effectively creating a prepared request that already
    /// holds everything needed to execute and parse the request
    /// (i.e. a reference to the client `C` and a closure that
    /// will parse the raw response into the output value type `V`).
    fn into_bound_typed_request<F, Fut>(self, parser_closure: F) -> BoundTypedRequest<'c, C, V, E>
    where
        F: FnOnce(RawResponse) -> Fut + 'static,
        Fut: Future<Output = Result<V, E>> + Send + 'static;
}

impl<'c, C, V, E> IntoBoundTypedRequest<'c, C, V, E> for BoundRawRequest<'c, C>
where
    C: KolomoniHttpClient,
    V: 'static,
    E: ResponseValueError + 'static,
{
    fn into_bound_typed_request<F, Fut>(self, parser_closure: F) -> BoundTypedRequest<'c, C, V, E>
    where
        F: FnOnce(RawResponse) -> Fut + 'static,
        Fut: Future<Output = Result<V, E>> + Send + 'static,
    {
        BoundTypedRequest::new(
            self.client,
            self.request.into_typed_request(parser_closure),
        )
    }
}
